### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by technicalshadow** [aron-tn/Mega-Bot#2]
$ python v2.py
  File "v2.py", line 59
    print "   %s[%s+%s]%s %s : %s"%(la7mar,lazra9,la7mar,la5dhar,y,x)
                                 ^
SyntaxError: invalid syntax

**Comment by KroadD** [comment]
You need to use Python 2.7 in order to make it work.

**Comment by aron-tn** [comment]
Yup download python 2.7.1 it will be work
