### ISSUE TITLE
Can't open file tool/ups.php.jd

### ISSUE THREAD

**Issue by ka1337** [aron-tn/Mega-Bot#4]
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.

[1] http://www.XXX.de - Unknown

**Comment by ka1337** [comment]
Again:

Can't open file tool/BackDoor.jpg: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.
Can't open file tool/ups.php.jd: No such file or directory at /usr/local/share/perl/5.26.1/LWP/UserAgent.pm line 479.

**Comment by skrewmerunning** [comment]
was a solution ever found for this?
